spring:
  application:
    name: CinemaHub2

  mail:
    host: smtp.gmail.com
    username: rockak387@gmail.com
    password: "juaj ahpu cpvu wynm" # Make sure this is correctly quoted if there are spaces in the password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/cinemahub4
    username: root
    password: root123

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update



  #      ddl-auto=create:
  redis:
    host: localhost
    port: 6379


logging:
  level:
    root: INFO  # Default log level for all
    com..example.cinemahub2: DEBUG  # Specific package (you can set your base package here)